services:
  - type: web
    name: yuzu-smash-ranking
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 4 --timeout 120 app:app
    envVars:
      - key: SECRET_KEY
        sync: false
