services:
  - type: web
    name: yuzu-smash-ranking
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: KOFI_VERIFICATION_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: ADMIN_DISCORD_ID
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: NODE_ENV
        value: production
